name: Server Deployement Pipeline
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_SERVER_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_SERVER_PROJECT_ID }}
on:
    push:
        branches: [main]

jobs:

    avoid_reduncy:
      runs-on: ubuntu-22.04
      steps:
        - name: Cancel Previous Runs
          uses: styfle/cancel-workflow-action@0.9.1
          with: 
            access_token: ${{github.token}}

    build: 
      runs-on: ubuntu-22.04
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - uses: actions/setup-node@v3
          with:
            node-version: 18
        - name: Install dependencies
          run: cd Server && npm ci
        - name: Build
          run: cd Server && npm run build 
        - uses: actions/upload-artifact@v2
          with:
            name: build
            path: ./Server/build           
   
    deploy:
        needs: [build]
        runs-on: ubuntu-22.04  
        steps:
          - uses: actions/checkout@v2
          - name: Install Vercel CLI
            run: cd Server && npm install --global vercel@latest
          - name: Install dependencies
            run: cd Server && npm ci  
          - name: Pull Vercel Environment Information
            run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
          - uses: actions/download-artifact@v2
            with:
              name: build
              path: build
          - name: Deploy Project Artifacts to Vercel
            run: vercel deploy --prod --token=${{ secrets.VERCEL_TOKEN }}